#include <wdm.h>
#include <Ntddkbd.h>

#ifndef PORTACSIOCTL 
#define PORTACSIOCTL 

#define PORTACS_IOCTL_INDEX  0x800 // for memory 

#define IOCTL_SPECKER_ON  CTL_CODE(  FILE_DEVICE_UNKNOWN, PORTACS_IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_SPECKER_OFF  CTL_CODE(FILE_DEVICE_UNKNOWN, PORTACS_IOCTL_INDEX+1, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_GET_CMOSTIME  CTL_CODE(FILE_DEVICE_UNKNOWN, PORTACS_IOCTL_INDEX+2, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#endif 
typedef struct{
	PDEVICE_OBJECT NextLayerDeviceObject;
	ULONG Flags;
	PDEVICE_OBJECT TopOfStack;
	PDEVICE_OBJECT  PDO;

}DEVICE_EXTENSION, *PDEVICE_EXTENSION;
typedef struct
{
	LIST_ENTRY listNode;
	char keyData;
	char keyFlags;
} KEY_DATA;
